CREATE DATABASE JigitalclouN

USE JigitalclouN

CREATE TABLE MsStaff
(
StaffID CHAR(9) PRIMARY KEY CHECK (StaffID LIKE 'JCN-R[0-2][1-2][0-9][0-9]'),
StaffName VARCHAR(50) NOT NULL,
StaffGender VARCHAR(50) NOT NULL,
StaffEmail VARCHAR(11) CHECK(StaffEmail LIKE '[A-Z][A-Z][A-Z]@[A-Z][A-Z][A-Z].[A-Z][A-Z][A-Z]'),
StaffDOB DATE NOT NULL,
StaffPhoneNumber CHAR(12) NOT NULL,
StaffAddress VARCHAR(50) NOT NULL,
StaffSalary DECIMAL(10,2) CHECK(StaffSalary > 3500000 AND StaffSalary < 20000000) NOT NULL
)

CREATE TABLE MsCustomer
(
CustomerID CHAR(9) PRIMARY KEY CHECK (CustomerID LIKE 'JCN-C[3-7][1-2][0-9][0-9]'),
CustomerName VARCHAR(50) NOT NULL,
CustomerGender VARCHAR(50) NOT NULL,
CustomerEmail VARCHAR(11) CHECK(CustomerEmail LIKE '[A-Z][A-Z][A-Z]@[A-Z][A-Z][A-Z].[A-Z][A-Z][A-Z]'),
CustomerDOB DATE NOT NULL,
CustomerPhoneNumber CHAR(12) NOT NULL,
CustomerAddress VARCHAR(50) NOT NULL,
)


CREATE TABLE MsLocation
(
LocationID CHAR(9) PRIMARY KEY CHECK (LocationID LIKE 'JCN-L[3-7][1-2][0-9][0-9]'),
City VARCHAR(50) NOT NULL,
Country VARCHAR(50) NOT NULL,
ZipCode INT NOT NULL,
Latitude DECIMAL(6,4) CHECK (Latitude >= -90 AND Latitude <= 90 )NOT NULL,
Longtitude DECIMAL(9,6) CHECK (Longtitude >= -180 AND Longtitude <= 180)NOT NULL
)


CREATE TABLE MsMemory
(
MemoryID CHAR(9) PRIMARY KEY CHECK (MemoryID LIKE 'JCN-M[3-7][1-2][0-9][0-9]'),
MemoryProductName VARCHAR(50) NOT NULL,
MemoryModelCode VARCHAR(50) NOT NULL,
MemoryPrice INT NOT NULL,
MemoryfrequencyMHz INT CHECK(MemoryFrequencyMHz BETWEEN 1000 AND 5000) NOT NULL,
MemoryCapacityGB INT CHECK(MemoryCapacityGB BETWEEN 1 AND 256) NOT NULL
)

CREATE TABLE MsProcessor
(
ProcessorID CHAR(9) PRIMARY KEY CHECK (ProcessorID LIKE 'JCN-P[3-7][1-2][0-9][0-9]'),
ProcessorName VARCHAR(50) NOT NULL,
ProcessorModelCode VARCHAR(50) NOT NULL,
ProcessorPrice INT NOT NULL,
ProcessorClockSpeedMHz INT CHECK(ProcessorClockSpeedMHz BETWEEN 1500 AND 6000)NOT NULL,
ProcessorNumberCores INT CHECK (ProcessorNumberCores BETWEEN 1 AND 24) NOT NULL,
)

CREATE TABLE MsServer
(
ServerID CHAR(9) PRIMARY KEY CHECK (ServerID LIKE 'JCN-V[3-7][1-2][0-9][0-9]'),
MemoryID CHAR(9) FOREIGN KEY REFERENCES MsMemory(MemoryID) ON UPDATE CASCADE ON DELETE CASCADE,
ProcessorID CHAR(9) FOREIGN KEY REFERENCES MsProcessor(ProcessorID) ON UPDATE CASCADE ON DELETE CASCADE,
LocationID CHAR(9) FOREIGN KEY REFERENCES MsLocation(LocationID) ON UPDATE CASCADE ON DELETE CASCADE,
ServerPrice INT NOT NULL
)

CREATE TABLE RentalTransactionHeader
(
RentalID CHAR(9) PRIMARY KEY CHECK (RentalID LIKE 'JCN-R[0-2][1-2][0-9][0-9]'),
CustomerID CHAR(9) FOREIGN KEY REFERENCES MsCustomer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
StaffID CHAR(9) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
StartingDate DATE CHECK (StartingDate >= '2012-01-01' AND StartingDate <= GETDATE())
)

CREATE TABLE RentalTransactionDetail
(
RentalID CHAR(9) FOREIGN KEY REFERENCES RentalTransactionHeader(RentalID) ON UPDATE CASCADE ON DELETE CASCADE,
ServerID CHAR(9) FOREIGN KEY REFERENCES MsServer(ServerID) ON UPDATE CASCADE ON DELETE CASCADE,
RentalDuration INT CHECK (RentalDuration > 0) NOT NULL
)

CREATE TABLE SaleTransactionHeader
(
SaleID CHAR(9) PRIMARY KEY CHECK (SaleID LIKE 'JCN-S[0-2][1-2][0-9][0-9]'),
CustomerID CHAR(9) FOREIGN KEY REFERENCES MsCustomer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
StaffID CHAR(9) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
TransactionDate DATE NOT NULL
)

CREATE TABLE SaleTransactionDetail
(
SaleID CHAR(9) FOREIGN KEY REFERENCES SaleTransactionHeader(SaleID) ON UPDATE CASCADE ON DELETE CASCADE,
ServerID CHAR(9) FOREIGN KEY REFERENCES MsServer(ServerID) ON UPDATE CASCADE ON DELETE CASCADE,
)